name: firestore_serializable
description: 'Generate fromMap(), fromSnapshot() and toMap() methods for your Firestore data models using this library. Based on source_gen, similar to json_serializable'
version: 0.0.11
homepage: https://www.github.com/dartclub/firestore_dart
environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  firestore_annotations: ^0.0.2
  build: '>=0.12.0 <2.0.0'  
  source_gen: ^0.9.4+7
  analyzer: ^0.39.4

dev_dependencies:
  build_test: ^0.10.8
  build_runner: ^1.5.0
  test: ^1.0.0
  build_verify: ^1.1.1
  firestore_api:
    git:
      url: git://github.com/dartclub/firestore_dart.git
      path: firestore_api