name: firestore_functions
description: interop for firebase_functions_interop
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_functions_interop:
    git: https://github.com/grundid/firebase-functions-interop.git
  firebase_admin_interop: ^2.1.0
  node_interop: ^1.0.3
  firestore_api:
    git:
      url: https://github.com/dartclub/firestore_dart
      path: firestore_api
  firestore_node:
    git:
      url: https://github.com/dartclub/firestore_dart
      path: firestore_node
